global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "fastapi"
    metrics_path: "/metrics"
    scheme: "http"
    static_configs:
      - targets: ["192.168.200.1:8000"]

  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]
